# Ders Planı

**Öğretim elemanı:** Prof. Dr. Deniz İnan

**e-posta:** denizlukuslu@marmara.edu.tr

**Ders saati ve yeri:** Çarşamba 08:30-12:20 A012 

**Ders amacı:** İstatistiksel Kalite Kontrol tarihçesi, yöntemler ve işleyiş hakkında bilgi sahibi olmak, R uygulamaları ile güncel hayat uygulamaları gerçekleştirmek

<br>

**Kaynaklar:** 

- [Introduction to Statistical Quality Control - Douglas C. Montgomery](http://endustri.eskisehir.edu.tr/ipoyraz/TKY302/icerik/text%20book_montgomery_6th%20edition.pdf) 

- [Statistical Process Control - John S. Oakland](http://www.diliev.com/Home/materiali/KHEA/referati/6812268-Statistical-Process-Control-eBook-VG.pdf)

- İstatistiksel Kalite Kontrol Ders Notları - Erhan Öner

- [İstatistiksel Kalite Kontrol Ders Notları - Tuncay Özcan](http://auzefkitap.istanbul.edu.tr/kitap/endustrimuhlt_ue/istatistikselkalitekontrolu.pdf)

- [Kalite Planlama ve Kontrol Ders Notları - Kemal Subulan](https://kisi.deu.edu.tr/kemal.subulan/Kalite_Planlama_Kontrol_Week11_KS.pdf)

<br>

**Ders Planı:** 

- Terminoloji ve genel bakış

- Kalite öncüleri

- Çıkarımsal istatistik

- Kontrol grafikleri
  - Ölçülebilir değişkenler için kontrol diyagramları
  - Ölçülemeyen özellikler için kontrol diyagramları
  
- Proses yeterlilik analizi, CUSUM ve EWMA diyagramları

- Kabul örneklemesi

- R uygulamaları _(Uygulamalar her konu içeriğinde yer alacaktır.)_

